// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYaSsXfKZtvYlqMpFLGNlw25yDUvU7ta8',
    appId: '1:896077347174:web:ad4275431c69f15fc7f0a7',
    messagingSenderId: '896077347174',
    projectId: 'chat-app-cc783',
    authDomain: 'chat-app-cc783.firebaseapp.com',
    storageBucket: 'chat-app-cc783.appspot.com',
    measurementId: 'G-0GGGQY8646',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsptlGrcS91XTaXbuaLPPSvxT0iTx8Jr4',
    appId: '1:896077347174:android:ce0cca80db368c0bc7f0a7',
    messagingSenderId: '896077347174',
    projectId: 'chat-app-cc783',
    storageBucket: 'chat-app-cc783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2iphNEGeYCd09jfwGfdo4ZOCQZJsZgjc',
    appId: '1:896077347174:ios:5ee0ae0f92546a87c7f0a7',
    messagingSenderId: '896077347174',
    projectId: 'chat-app-cc783',
    storageBucket: 'chat-app-cc783.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYaSsXfKZtvYlqMpFLGNlw25yDUvU7ta8',
    appId: '1:896077347174:web:4768e8c5fff0a94dc7f0a7',
    messagingSenderId: '896077347174',
    projectId: 'chat-app-cc783',
    authDomain: 'chat-app-cc783.firebaseapp.com',
    storageBucket: 'chat-app-cc783.appspot.com',
    measurementId: 'G-42G7DMJ30G',
  );
}
